name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new feature or improvement.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: Describe your proposed solution.
    validations:
      required: true
